---
# install common server utilities

- name: run update
  sudo: yes
  apt: update_cache=yes

- name: run upgrade
  sudo: yes
  apt: upgrade=safe

- name: install packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - curl
    - exim4-daemon-light
    - fail2ban
    - git
    - htop
    - mailutils
    - monit
    - openssl
    - ufw
    - vim
    - zip

- name: reset firewall
  sudo: yes
  command: ufw --force reset
  tags: firewall

- name: allow firewall authorized ports
  sudo: yes
  command: ufw allow {{ item }}
  with_items: firewall
  tags: firewall

- name: enable firewall
  sudo: yes
  command: ufw --force enable
  tags: firewall

- name: apply exim4 configuration
  sudo: yes
  template: src=update-exim4.conf.conf.j2 dest=/etc/exim4/update-exim4.conf.conf
  tags: exim

- name: start exim4 with configuration
  sudo: yes
  action: service name=exim4 state=started enabled=yes
  tags: exim

- name: apply monit configuration
  sudo: yes
  template: src=monitrc.j2 dest=/etc/monit/monitrc
  tags: monit

- name: start monit with configuration
  sudo: yes
  action: service name=monit state=started enabled=yes
  tags: monit
