---
# INSTALL OPENSRF

- name: run update
  sudo: yes
  apt: update_cache=yes
  tags: opensrf

- name: run upgrade
  sudo: yes
  apt: upgrade=safe
  tags: opensrf

- name: install packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - autoconf
    - automake
    - build-essential
    - git
    - libtool
    - make
    - openssl
  tags: opensrf

- name: add host entries
  sudo: yes
  lineinfile: dest=/etc/hosts regexp="\s{{ item.hostname }}\s" line="{{ item.ip }} {{ item.hostname }} {{ item.alias }}" state=present
  with_items: opensrf_hosts
  tags: opensrf

- name: create the opensrf group
  sudo: yes
  group: name=opensrf gid=3000 state=present
  tags: opensrf

- name: create the opensrf user
  sudo: yes
  user: name=opensrf group=opensrf state=present shell=/bin/bash
  tags: opensrf

- name: add openils bin to path
  sudo_user: opensrf
  lineinfile: dest=/home/opensrf/.bashrc line="export PATH=$PATH:/openils/bin" owner=opensrf group=opensrf mode=0644 state=present
  tags: opensrf

- name: create the openils directory
  sudo: yes
  file: path=/openils owner=opensrf group=opensrf mode=0755 state=directory
  tags: opensrf

- name: download the opensrf repo
  sudo_user: opensrf
  git: repo=git://git.evergreen-ils.org/OpenSRF.git dest=/home/opensrf/OpenSRF version={{ opensrf_version }}
  tags: opensrf

- name: install the pre-reqs
  sudo: yes
  command: make -f src/extras/Makefile.install {{ opensrf_os_name }} chdir=/home/opensrf/OpenSRF
  tags: opensrf

- name: generate the configure script and makefiles
  sudo_user: opensrf
  command: autoreconf -i chdir=/home/opensrf/OpenSRF
  tags: opensrf

- name: configure and build opensrf
  sudo_user: opensrf
  shell: ./configure --prefix=/openils --sysconfdir=/openils/conf && make chdir=/home/opensrf/OpenSRF
  tags: opensrf

- name: install opensrf
  sudo: yes
  shell: make install chdir=/home/opensrf/OpenSRF
  tags: opensrf

- name: change ownership of root openils directory to opensrf
  sudo: yes
  file: path=/openils owner=opensrf group=opensrf state=directory recurse=yes
  tags: opensrf

- name: add to the system dynamic library path
  sudo: yes
  copy: content='/openils/conf' dest='/etc/ld.so.conf.d/opensrf.conf' owner=root group=root
  tags: opensrf

- name: set the system dynamic library path
  sudo: yes
  command: ldconfig
  tags: opensrf

- name: apply the ejabberd config file
  sudo: yes
  copy: src=ejabberd.cfg dest=/etc/ejabberd/ejabberd.cfg owner=root group=ejabberd mode=0640
  tags: opensrf

- name: ensure ejabberd is stopped then started at this point
  sudo: yes
  shell: service ejabberd stop && service ejabberd start && sleep 10
  tags: opensrf

- name: create the opensrf jabber users
  sudo: yes
  command: ejabberdctl register {{ item.type }} {{ item.host }} {{ opensrf_ejabberd_password }}
  with_items: opensrf_jabber_users
  ignore_errors: true
  tags: opensrf

- name: apply opensrf_core configuration settings
  sudo_user: opensrf
  template: src=opensrf_core.xml.j2 dest=/openils/conf/opensrf_core.xml
  tags: opensrf

- name: copy opensrf.xml in place
  sudo_user: opensrf
  command: cp /openils/conf/opensrf.xml.example /openils/conf/opensrf.xml creates=/openils/conf/opensrf.xml
  tags: opensrf

- name: apply srfsh.xml for opensrf
  sudo_user: opensrf
  template: src=srfsh.xml.j2 dest=/home/opensrf/.srfsh.xml
  tags: opensrf
